export const AUTH_SET_LOGIN_STATUS = "AUTH_SET_LOGIN_STATUS";
export const AUTH_SET_TOKEN_STATUS = "AUTH_SET_TOKEN_STATUS";
export const AUTH_SAVE_MY_USERNAME = "AUTH_SAVE_MY_USERNAME";

export const LOGIN_STATUS_LOGOUT   = "LOGOUT" ;
export const LOGIN_STATUS_LOADING  = "LOADING";
export const LOGIN_STATUS_SUCCEED  = "SUCCEED"; 



