export const WEBSOCKET_CREATE = "WEBSOCKET_CREATE";
export const WEBSOCKET_DESTROY = "WEBSOCKET_DESTROY";

export const WEBSOCKET_NEWMESSAGE = "WEBSOCKET_NEWMESSAGE";

export const WEBSOCKET_SET_ISEXPANDMENU = "WEBSOCKET_SET_ISEXPANDMENU" ;

export const WEBSOCKET_SELECT_CONTACT = "WEBSOCKET_SELECT_CONTACT";
export const WEBSOCKET_SELECT_GROUP = "WEBSOCKET_SELECT_GROUP";
export const WEBSOCKET_SELECT_MYCHATROOM = "WEBSOCKET_SELECT_MYCHATROOM" ;

export const WEBSOCKET_SET_CONTACTLIST  = "WEBSOCKET_SET_CONTACTLIST";


export const WEBRTC_ISINMEDIACALL = "WEBRTC_ISINMEDIACALL"

export const WEBRTC_ISCALLACCEPTED = "WEBRTC_ISCALLACCEPTED"

export const WEBRTC_SET_MEDIACALLSTATE = "WEBRTC_SET_MEDIACALLSTATE"

export const WEBRTC_SET_STREAM_REF = "WEBRTC_SET_STREAM_REF"

export const WEBSOCKET_SET_ISSHOWPANEL = 'WEBSOCKET_SET_ISSHOWPANEL'

