export const WEBSOCKET_MEDIACALL_STATE_IDLE = "idle"
export const WEBSOCKET_MEDIACALL_STATE_INVIDEOCALL = "inVideoCall"
export const WEBSOCKET_MEDIACALL_STATE_INVOICECALL = "inVoiceCall"
export const WEBSOCKET_MEDIACALL_STATE_MEDIACALLRECEIVED = "mediaCallReceived"

