export const AUTH_START = 'AUTH_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
export const AUTH_CHECKLOGIN_SUCCESS = 'AUTH_CHECKLOGIN_SUCCESS';
export const AUTH_CHECKLOGIN_FAIL = 'AUTH_CHECKLOGIN_FAIL';
export const AUTH_CHECKUSER_SUCCES = 'AUTH_CHECKUSER_SUCCES';
export const AUTH_CHECKUSER_FAIL = 'AUTH_CHECKUSER_FAIL';
export const AUTH_CHECKEMAIL_SUCCES = 'AUTH_CHECKUSER_SUCCES';
export const AUTH_CHECKEMAIL_FAIL = 'AUTH_CHECKUSER_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const WSS_SEND = 'WSS_SEND';
